### ISSUE TITLE
Two days in a row. Is the end near?

### ISSUE THREAD

**Issue by kieckhafer** [top-performers/github-bet#11]
<img width="634" alt="github_system_status" src="https://user-images.githubusercontent.com/4482263/26864821-f3397872-4b0e-11e7-8ad4-44bc3d66ab1c.png">

**Comment by i-a-n** [comment]
#lightsareflickering #downandtotheright #📉

**Comment by ItsMeAra** [comment]
They were just trying out Managed WordPress hosting for a bit, they know better now.

**Comment by i-a-n** [comment]
should've sprung for the TRIPPPPLE BOOST
