### ISSUE TITLE
GitHub circling the toilet, misses revenue targets, VP of social impact quits

### ISSUE THREAD

**Issue by i-a-n** [top-performers/github-bet#12]
Lot of good stuff here: https://www.buzzfeed.com/carolineodonovan/an-executive-departure-at-github-reignites-employee

> At the end of June, a member of Github’s finance team posted a plan for a new equity grant program on GitHub’s internal message board. The plan, according to the announcement, was meant to “reward high-performing Hubbers with an increased stake in the company,” according to screenshots of the announcement reviewed by BuzzFeed News. Here’s an excerpt:

_"We plan for this to be an annual program tied to the year-end performance review process. Each year, the available pool of merit-based stock options will be determined based on company performance in the prior year. Generally speaking, not every Hubber will receive a merit-based grant. When the company’s performance is strong, we will likely be able to award more Hubbers with merit-based grants, but the reverse is true when company performance doesn’t hit target. For FY17, GitHub reached 88% of our revenue target. Each Hubber’s eligibility and/or number of options will depend on their role, scope of impact, and performance"_

> Several GitHub employees who spoke with BuzzFeed News said Wanstrath’s unusually stern tone surprised them, as did his determination to roll out the equity grant program despite employee consternation. Wanstrath declined to be interviewed for this story, but in a statement, a spokesperson for GitHub said, “Performance-based equity compensation programs are standard and widely utilized to incentivize and reward employees. We're focused on designing and implementing our program in a way that is consistent with our company values.”

sounds pretty familiar... #itsgotime

.... #goingdownandtotheright

**Comment by ItsMeAra** [comment]
![Wrong](https://media.giphy.com/media/3oz8xLd9DJq2l2VFtu/giphy.gif)

**Comment by i-a-n** [comment]
Hahahahahahahahaha
