### ISSUE TITLE
A GitHub programmer turned down a severance check?! CANCEL ORDER!

### ISSUE THREAD

**Issue by vram1980** [top-performers/github-bet#13]
You know its bad when you turn down free money: [http://www.businessinsider.com/fired-github-programmer-coraline-ada-ehmke-speaks-out-2017-7](http://www.businessinsider.com/fired-github-programmer-coraline-ada-ehmke-speaks-out-2017-7)

**Comment by i-a-n** [comment]
beginning of the end
