### ISSUE TITLE
"GitHub, Struck by Record-Breaking DDoS, Walks It Off"

### ISSUE THREAD

**Issue by kieckhafer** [top-performers/github-bet#15]
📈📈📈

![image](https://user-images.githubusercontent.com/4482263/36915876-161a5264-1e07-11e8-892f-9763dd6f118c.png)

https://gizmodo.com/github-struck-by-record-breaking-ddos-walks-it-off-1823443461

**Comment by i-a-n** [comment]
damn didn't realize they had cloudtech™

**Comment by ItsMeAra** [comment]
(mt) One &trade;

"This app is better than my Phone app. I don't have to enter a number I just open the app and click call. Fantastic!" -Steve Ballmer

**Comment by i-a-n** [comment]
hahaha hahahah godaamn
