### ISSUE TITLE
Microsoft confirms it has acquired GitHub for $7.5 billion

### ISSUE THREAD

**Issue by ItsMeAra** [top-performers/github-bet#17]
I mean... this means I win right? Ready for Vegas in July let me know when its booked dawg. 😂😂

**Comment by i-a-n** [comment]
fuuuuuuuuuuck

**Comment by i-a-n** [comment]
I need a MOMENT to process this

**Comment by vram1980** [comment]
7.5 billion.... WOW

**Comment by i-a-n** [comment]
okay I think this means you win. but I get until the date the bet ends (Feb 18, 2019) to book the trip. hahaha. fuck.

taking a hard L here.

**Comment by ItsMeAra** [comment]
![ara-thumbz-wrap](https://cloud.githubusercontent.com/assets/308142/24175812/8e231b5a-0e55-11e7-9236-dc0c88fb18a6.jpg)
