### ISSUE TITLE
Reminder: You lost. I won. February is coming. :) 

### ISSUE THREAD

**Issue by ItsMeAra** [top-performers/github-bet#18]
Just a friendly reminder. 😄

**Comment by i-a-n** [comment]
proposing Sep 12, 13, 14, or 13, 14, 15. top performer Vinson will be there too.

obviously everyone's invited (@vram1980 @kieckhafer @setzen), but I'm only paying for @ItsMeAra ... haha

**Comment by i-a-n** [comment]
shit Setzen doesn't have a github, who the hell did I just invite to Vegas lol

**Comment by kieckhafer** [comment]
Let us know the final dates, I'd be down for a Top Performer reunion (+ some random guy named Jon Setzen who isn't the one and only true Jon Setzen).

**Comment by ItsMeAra** [comment]
I'm good with either set of days. @i-a-n you're call haha

**Comment by i-a-n** [comment]
![screenshot1550758738 1x](https://user-images.githubusercontent.com/1937355/53175360-ca412680-35b9-11e9-8097-e30edc021979.png)

@ItsMeAra 

if you want to drive, I'll cover your gas. if you want to fly, send me your desired airport and whatever else I need to book a flight.

fuck github. hahah.

**Comment by i-a-n** [comment]
oh I'll even sleep on the couch, they've got comfy furniture

**Comment by ItsMeAra** [comment]
LESS GOOOO
![vegas baby](https://media.giphy.com/media/gqWFQsqWXktGg/giphy.gif)

**Comment by i-a-n** [comment]
I still can't believe this shit. how did Github do so well??

I'm probably gonna be booking your ticket through GitHub Flights, that's how wrong I was lol
