### ISSUE TITLE
Github doing big thangz!!!

### ISSUE THREAD

**Issue by ItsMeAra** [top-performers/github-bet#4]
https://github.com/universe-2016

**Code Reviews**  
Professional-grade code review has come to Pull Requests. Draft multiple comments, and submit once. Give your teammate a `:shipit:`, or request changes. Protect your branches from unreviewed code.

**Project Management aka Kanban Board**  
Projects seamlessly integrates project management into your development process. You can reference every Issue and Pull Request with a card—and with Notes, you’ll never miss an idea from your weekly planning sync.

**Profile Page Updates**  
GitHub profiles show your life and career as a developer. We’ve taken the contribution graph to new heights with your GitHub timeline—a snapshot of your most important triumphs and contributions.

![](https://media.giphy.com/media/3o7qDSOvfaCO9b3MlO/giphy.gif)

**Comment by i-a-n** [comment]
![](https://union.io/images/repo/20160915-00--6f5660.jpg)
