### ISSUE TITLE
Github looking for secondary round of funding; may be down-round

### ISSUE THREAD

**Issue by i-a-n** [top-performers/github-bet#5]
https://techcrunch.com/2016/10/07/github-is-raising-a-secondary-round/

Might significantly drop GitHub's valuation. Microsoft in talks for some kind of integration, possible acquisition.

Looks like the ship is still sinking!

**Comment by i-a-n** [comment]
![](http://i.giphy.com/v0YiARQxj1yc8.gif)

**Comment by ItsMeAra** [comment]
Still doesn't drop anywhere near where you need it to be at! 

Though if MS takes over I will shoot myself in the face. _sigh_

**Comment by vram1980** [comment]
If MS takes over it will finally make some real dollars #enterprise #everyCashRegisterOnThePlanetRunsWindows #thinkAboutIt
