### ISSUE TITLE
Github cuts 5% of workforce; "focusing on Enterprise sales"

### ISSUE THREAD

**Issue by i-a-n** [top-performers/github-bet#6]
Looks like github has taken up the "whale strategy":

> A company spokesperson said the layoffs were part of Github’s focus on enterprise sales. “We are refocusing our resources in order to serve our customers more efficiently,” the spokesperson said.

http://fortune.com/2016/12/08/github-cuts-sales-staff/

#RIP #sinkingship #thatsawrap #📉

**Comment by vram1980** [comment]
God tier PR

**Comment by i-a-n** [comment]
No response yet from @ItsMeAra? Is he taking the L on this already?

**Comment by ItsMeAra** [comment]
Gotta drain the swamp and get rid of the dead weight. #noWorries

**Comment by i-a-n** [comment]
Fuuuuuuuck
