### ISSUE TITLE
GitHub lost $66M in nine months of 2016...

### ISSUE THREAD

**Issue by vram1980** [top-performers/github-bet#7]
https://www.bloomberg.com/news/articles/2016-12-15/github-is-building-a-coder-s-paradise-it-s-not-coming-cheap

> The VC-backed unicorn startup lost $66 million in nine months of 2016, financial documents show.

# That's a wrap!

**Comment by ItsMeAra** [comment]
Takes money to build a coder's paradise! 2017 gonna be LIT!!

![image](https://media.giphy.com/media/3oEduHh0njlxkeqJVK/giphy.gif)

**Comment by i-a-n** [comment]
![Chris Wanstrath](http://i0.wp.com/img.logmi.jp/wp-content/uploads/2015/06/GitHub_catch.jpg)

> “What happened to 2015?” says the 31-year-old co-founder and chief executive officer. “Nothing was getting done, maybe? I shouldn’t say that. Strike that.”

Oh boy.

> “The whole product road map, we have all of our shit together in a way that we’ve never had together. I’m pretty elated right now with the way things are going,” says Wanstrath. 

That's some Silicon Valley shit right there gents. #goingdownwiththeship

**Comment by ItsMeAra** [comment]
elated!! wooooo!!! how is this bad?

**Comment by vram1980** [comment]
![image](https://d1zjcuqflbd5k.cloudfront.net/files/acc_88212/rKsw?response-content-disposition=inline;%20filename=Screen%20Shot%202016-12-16%20at%2009.30.49.png&Expires=1481909752&Signature=AuedZWRdJ6W3JOxJUmU-cdUlxYaaM0hvYtUUsQSOsi0q9BVGpscQg2fEJI2r7DvNvkZBp6XeqD04ui7bP5rXZNaRv4BNutVxdG57p2~cBuT5M5Ee5jN6T3DttxM3U0~Xwn54OMmysm7OBczpXnNyG6ynhgTg~JUo3T9L2RKXwCw_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)
