### ISSUE TITLE
GitLab shits the bed, deletes 300GB of customer data, no backups

### ISSUE THREAD

**Issue by i-a-n** [top-performers/github-bet#8]
https://www.theregister.co.uk/2017/02/01/gitlab_data_loss/

>According to The Register a folder containing 300GB of live production data was erroneously deleted by a GitLab sysadmin — with just 4.5GB remaining by the time the delete command was cancelled.

>So in other words, out of 5 backup/replication techniques deployed none are working reliably or set up in the first place.

DAM SON, GitLab is #FINISHED

**Comment by ItsMeAra** [comment]
LOl #thatsAWRAP
