### ISSUE TITLE
GitLab acquires Gitter; plans to open-source it

### ISSUE THREAD

**Issue by i-a-n** [top-performers/github-bet#9]
In a resounding show of strength and benevolence, GitLab just bought Gitter and wisely and generously decided to open-source it:

http://blog.gitter.im/2017/03/15/gitter-gitlab-acquisition/

Unlike the dying GitHub, which is rife with in-fighting and making everything proprietary, GitLab is clearly on the up-and-up. #RIPgithub

Also there is a #top-performers chatroom on Gitter. Follow the instructions on http://gitter.im and joint he chatroom `#top-performers/Lobby` to discuss GitHub's dying days.

**Comment by ItsMeAra** [comment]
Slack > Gitter . *YAWN* reaching.jpg

**Comment by i-a-n** [comment]
only thing I'm reaching for is the sunscreen for that sweet Vegas trip you're buying me when I win this bet

**Comment by ItsMeAra** [comment]
Name 3 people that use Gitlab over Github... go ahead... I'll wait... hahah

**Comment by vram1980** [comment]
What the hell is a gitter
